<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('registration'));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form); ?>

<table>
    <tr>
        <td><?= $form->get('username')->getLabel()?>: </td>
        <td style="width: 200px"><?= $this->formElement($form->get('username')) ?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElementErrors($form->get('username'));?></td>
    </tr>
    <tr>
        <td><?= $form->get('password')->getLabel()?>: </td>
        <td><?= $this->formElement($form->get('password')) ?></td>

    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElementErrors($form->get('password'));?></td>
    </tr>
    <tr>
        <td><?= $form->get('confirmPassword')->getLabel()?>: </td>
        <td><?= $this->formElement($form->get('confirmPassword')) ?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElementErrors($form->get('confirmPassword'));?></td>
    </tr>
    <tr>
        <td><?= $form->get('email')->getLabel()?>: </td>
        <td><?= $this->formElement($form->get('email')) ?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElementErrors($form->get('email'));?></td>
    </tr>
    <tr>
        <td><?= $form->get('firstName')->getLabel()?>: </td>
        <td><?= $this->formElement($form->get('firstName')) ?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElementErrors($form->get('firstName'));?></td>
    </tr>
    <tr>
        <td><?= $form->get('lastName')->getLabel()?>: </td>
        <td><?= $this->formElement($form->get('lastName')) ?></td>
        <td><?php echo $this->formElementErrors($form->get('lastName'));?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElementErrors($form->get('lastName'));?></td>
    </tr>
    <tr>
        <td><?= $form->get('aboutMe')->getLabel()?>: </td>
        <td><?= $this->formElement($form->get('aboutMe')) ?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElementErrors($form->get('aboutMe'));?></td>
    </tr>
    <tr>
        <td>Enter captcha: </td>
        <td><?= $this->formElement($form->get('captcha')) ?></td>
    </tr>
    <tr>
        <td colspan="2"><?php echo $this->formElementErrors($form->get('captcha'));?></td>
    </tr>
    <tr>
        <td></td>
        <td><?php echo $this->formElement($form->get('submit')); ?></td>
    </tr>
    <?php echo $this->formElement($form->get('csrfReg')); ?>
</table>


<?php echo $this->form()->closeTag($this->form); ?>
